name: first-github-action
on: push
jobs:
  updateCv:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npx resumed render resume.json --theme mooser
      - run: mkdir public
      - run: mv resume.html public/index. html
